//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.20 at 03:13:22 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://springworkout.workouts.virtusa.com/")
package com.virtusa.workouts.springworkout.types;
